// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in atlasgo.io/entprint/ent/runtime.go

const (
	Version = "v0.10.2-0.20220308213213-342088fcce2a"           // Version of ent codegen.
	Sum     = "h1:dtn0Weu1fu0Zt8tQyQcoGZ9u1vy8rSC45Kcd/K3o/C8=" // Sum of ent codegen.
)
